### ISSUE TITLE
[KubernetesDiscoveryClient] Support cluster-ip as service-instance

### ISSUE THREAD

**Issue by luckyswede** [micronaut-projects/micronaut-kubernetes#185] opened 2020-09-23 13:54 UTC
Hi,
In Micronaut 2.0.x the Kubernetes discovery get pod ip's in the service-instance list that is returned from the discovery-client. In one of our cases where we have a few thousand requests per second to another service we get problems when pods are recycled, because the pod list is apparently not up to date.
On the other hand, with Micronaut 1.2.x that we also run, which uses cluster-ip's, we dont have that same issue. So it seems that the cluster-ip has a more up-to-date pod state.

Would it be possible to make the k8s discovery client configurable wrt returning cluster-ip's or pod-ip's in the service-instance list?

**Comment by graemerocher** [comment] 2020-09-23 14:37
Probably doable

**Comment by alvarosanchez** [comment] 2020-09-24 17:07
To be precise, what the current implementation uses is the `EndpointsSubset.addresses`. Quoting Kubernetes documentation:

> IP addresses which offer the related ports that are marked as ready. These endpoints should be considered safe for load balancers and clients to utilize

The reason to not use the `Service.clusterIP` is consistency: all Micronaut service discovery implementations use Micronaut's load balancing capabilities.

So in this case, the issue is really an outdated service list, and therefore, implementing #186 by watching endpoints changes will fix this issue.

**Comment by luckyswede** [comment] 2020-09-24 18:11
@alvarosanchez  We did not have caching enabled when we encountered the problem with unavailable pods in the service list. So from what I understand the discovery-client refreshed the service list on each request. One pod was unavailable nonetheless. Maybe the k8s api server state was not propagated fast enough, I dont know. 
At the same time we had Micronaut 1.2.x-based apps that used the same service (with a failing pod) via the cluster-ip, and those apps experienced much fewer issues. 15 instances of 1.2-based apps had about 500 connection errors in total, at the same time a single 2.0.2 based canary app had connection 2000 errors. The traffic was evenly distributed over those 16 instances.

**Comment by alvarosanchez** [comment] 2020-09-24 20:39
If you really want to use the cluster IP, you can use the records created by `kube-dns`, eg:

```java
@Client("my-service.my-namespace.svc.cluster.local")
```

**Comment by graemerocher** [comment] 2020-09-25 06:07
@alvarosanchez maybe worth documenting that somewhere if that is viable fix. @luckyswede does that work for you?

**Comment by graemerocher** [comment] 2020-09-25 06:08
also does that need to be in `${..}`?

**Comment by luckyswede** [comment] 2020-09-25 06:33
Yes, we're going for a similar solution, we've implemented a discovery-client that creates a k8s service-url from the service-id. It's more "plug-n-play", we dont have to change the client annotations or add config entries.

**Comment by luckyswede** [comment] 2020-09-25 06:44
@graemerocher a related question, what is the contract for `DiscoveryClient.getServiceIds`? Is it supposed to return all service-ids that it has "seen" in requests to `getInstances`? Or a list of all service-ids it supports (which is not possible if the service-instance is calculated from the service-id)?

**Comment by alvarosanchez** [comment] 2020-09-25 07:03
> also does that need to be in `${..}`?

No, it doesn't. Given a service `my-service` in a namespace `my-namespace`, `my-service.my-namespace.svc.cluster.local` will be a DNS `A` record that will resolve to the service cluster IP.

**Comment by pgressa** [comment] 2021-01-03 19:10
addressed in https://github.com/micronaut-projects/micronaut-kubernetes/pull/215

**Closed** 2021-01-20 09:20 UTC
Labels: type: improvement
